// AUTO-GENERATED BY scripts/generate_isa.js
// DO NOT EDIT MANUALLY

use crate::vm::Vm;
use crate::stack::VmError;
use crate::handlers::*;

pub type HandlerFn = fn(&mut Vm) -> Result<bool, VmError>;

pub fn get_dispatch_table() -> [HandlerFn; 256] {
    let mut table: [HandlerFn; 256] = [op_invalid; 256];
    table[0] = op_pushint;
    table[1] = op_pop;
    table[2] = op_dup;
    table[3] = op_pushfloat;
    table[4] = op_pushstring;
    table[5] = op_pushbool;
    table[6] = op_pushnull;
    table[7] = op_loadlocal;
    table[8] = op_storelocal;
    table[9] = op_add;
    table[10] = op_sub;
    table[11] = op_mul;
    table[12] = op_div;
    table[13] = op_eq;
    table[14] = op_neq;
    table[15] = op_lt;
    table[16] = op_gt;
    table[17] = op_lte;
    table[18] = op_gte;
    table[19] = op_and;
    table[20] = op_or;
    table[21] = op_not;
    table[22] = op_bitand;
    table[23] = op_bitor;
    table[24] = op_bitxor;
    table[25] = op_bitnot;
    table[26] = op_shl;
    table[27] = op_shr;
    table[28] = op_jump;
    table[29] = op_jumpif;
    table[30] = op_jumpifnot;
    table[31] = op_newobject;
    table[32] = op_newlist;
    table[33] = op_listpush;
    table[34] = op_getmember;
    table[35] = op_setmember;
    table[36] = op_length;
    table[37] = op_hash256;
    table[38] = op_encryptaes;
    table[39] = op_jsonstringify;
    table[40] = op_call;
    table[41] = op_return;
    table[42] = op_callnative;
    table[43] = op_halt;
    table[44] = op_concat;
    table[45] = op_compareandadd;
    table[46] = op_swapandmul;
    table[47] = op_jumpandmul;
    table[48] = op_swap;
    table[49] = op_rotate;
    table[50] = op_drop2;
    table
}
