// AUTO-GENERATED BY scripts/generate_isa.js
// DO NOT EDIT MANUALLY

use crate::vm::Vm;
use crate::stack::VmError;
use crate::handlers::*;

pub type HandlerFn = fn(&mut Vm) -> Result<bool, VmError>;

pub fn get_dispatch_table() -> [HandlerFn; 256] {
    let mut table: [HandlerFn; 256] = [op_invalid; 256];
    table[81] = op_pushint;
    table[2] = op_pop;
    table[184] = op_dup;
    table[185] = op_pushfloat;
    table[70] = op_pushstring;
    table[121] = op_pushbool;
    table[244] = op_pushnull;
    table[162] = op_loadlocal;
    table[36] = op_storelocal;
    table[37] = op_add;
    table[249] = op_sub;
    table[106] = op_mul;
    table[18] = op_div;
    table[248] = op_eq;
    table[158] = op_neq;
    table[147] = op_lt;
    table[186] = op_gt;
    table[64] = op_lte;
    table[180] = op_gte;
    table[105] = op_and;
    table[143] = op_or;
    table[201] = op_not;
    table[47] = op_bitand;
    table[208] = op_bitor;
    table[207] = op_bitxor;
    table[200] = op_bitnot;
    table[88] = op_shl;
    table[132] = op_shr;
    table[194] = op_jump;
    table[4] = op_jumpif;
    table[140] = op_jumpifnot;
    table[156] = op_newobject;
    table[193] = op_newlist;
    table[52] = op_listpush;
    table[242] = op_getmember;
    table[96] = op_setmember;
    table[72] = op_length;
    table[202] = op_hash256;
    table[191] = op_encryptaes;
    table[26] = op_jsonstringify;
    table[46] = op_call;
    table[25] = op_return;
    table[167] = op_callnative;
    table[97] = op_halt;
    table[206] = op_concat;
    table[111] = op_compareandadd;
    table[6] = op_swapandmul;
    table[53] = op_jumpandmul;
    table[9] = op_swap;
    table[217] = op_rotate;
    table[68] = op_drop2;
    table
}
