// AUTO-GENERATED BY scripts/generate_isa.js
// DO NOT EDIT MANUALLY

use crate::vm::Vm;
use crate::stack::VmError;
use crate::handlers::*;

pub type HandlerFn = fn(&mut Vm) -> Result<bool, VmError>;

pub fn get_dispatch_table() -> [HandlerFn; 256] {
    let mut table: [HandlerFn; 256] = [op_invalid; 256];
    table[33] = op_pushint;
    table[159] = op_pop;
    table[188] = op_dup;
    table[197] = op_pushfloat;
    table[36] = op_pushstring;
    table[100] = op_pushbool;
    table[244] = op_pushnull;
    table[78] = op_loadlocal;
    table[43] = op_storelocal;
    table[71] = op_add;
    table[230] = op_sub;
    table[25] = op_mul;
    table[0] = op_div;
    table[37] = op_eq;
    table[53] = op_neq;
    table[120] = op_lt;
    table[38] = op_gt;
    table[182] = op_lte;
    table[133] = op_gte;
    table[82] = op_and;
    table[109] = op_or;
    table[126] = op_not;
    table[234] = op_bitand;
    table[199] = op_bitor;
    table[76] = op_bitxor;
    table[47] = op_bitnot;
    table[239] = op_shl;
    table[108] = op_shr;
    table[176] = op_jump;
    table[207] = op_jumpif;
    table[96] = op_jumpifnot;
    table[7] = op_newobject;
    table[95] = op_newlist;
    table[210] = op_listpush;
    table[246] = op_getmember;
    table[93] = op_setmember;
    table[248] = op_length;
    table[49] = op_hash256;
    table[189] = op_encryptaes;
    table[144] = op_jsonstringify;
    table[52] = op_call;
    table[86] = op_return;
    table[245] = op_callnative;
    table[30] = op_halt;
    table[185] = op_concat;
    table[127] = op_compareandadd;
    table[3] = op_swapandmul;
    table[191] = op_jumpandmul;
    table[90] = op_swap;
    table[62] = op_rotate;
    table[66] = op_drop2;
    table
}
