const fs = require('fs');
const path = require('path');

const OPCODES = [
  "PushInt", "Pop", "Dup", "PushFloat", "PushString", "PushBool", "PushNull",
  "LoadLocal", "StoreLocal", "Add", "Sub", "Mul", "Div", "Eq", "Neq", "Lt", "Gt", "Lte", "Gte",
  "And", "Or", "Not", "BitAnd", "BitOr", "BitXor", "BitNot", "Shl", "Shr", "Jump", "JumpIf", "JumpIfNot",
  "NewObject", "NewList", "ListPush", "GetMember", "SetMember", "Length", "Hash256", "EncryptAES", "JSONStringify", "Call", "Return", "CallNative", "Halt", "Concat",
  "CompareAndAdd", "SwapAndMul", "JumpAndMul", "Swap", "Rotate", "Drop2"
];

// Phase 12: Code Renewability
// We use a Fisher-Yates shuffle to randomize the canonical ISA bytes from 0-255 on every build.
// This completely destroys the viability of static decompilation tools that map bytes to standard instructions.
// See Code Renewability for Native Software Protection, arxiv.org/abs/2003.00916.
const bytes = Array.from({length: 256}, (_, i) => i);
for (let i = 255; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    const temp = bytes[i];
    bytes[i] = bytes[j];
    bytes[j] = temp;
}

const opcodeValues = {};
for (let i = 0; i < OPCODES.length; i++) {
    opcodeValues[OPCODES[i]] = bytes[i];
}

// Generate crates/vm-core/src/opcodes.rs
let rustOutput = `// AUTO-GENERATED BY scripts/generate_isa.js
// DO NOT EDIT MANUALLY

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum OpCode {
`;

for (const op of OPCODES) {
    rustOutput += `    ${op} = 0x${opcodeValues[op].toString(16).padStart(2, '0').toUpperCase()},\n`;
}

rustOutput += `}

impl TryFrom<u8> for OpCode {
    type Error = ();

    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
`;

for (const op of OPCODES) {
    rustOutput += `            0x${opcodeValues[op].toString(16).padStart(2, '0').toUpperCase()} => Ok(OpCode::${op}),\n`;
}

rustOutput += `            _ => Err(()),
        }
    }
}
`;

fs.writeFileSync(path.join(__dirname, '../crates/vm-core/src/opcodes.rs'), rustOutput);

// Generate compiler/src/opcodes.ts
let tsOutput = `// AUTO-GENERATED BY scripts/generate_isa.js
// DO NOT EDIT MANUALLY

export enum OpCode {
`;

for (const op of OPCODES) {
    tsOutput += `    ${op} = 0x${opcodeValues[op].toString(16).padStart(2, '0').toUpperCase()},\n`;
}

tsOutput += `}
`;

fs.writeFileSync(path.join(__dirname, '../compiler/src/opcodes.ts'), tsOutput);

console.log("Randomized canonical ISA generated successfully.");

// Generate crates/vm-core/src/dispatch_table.rs
let dispatchTableContent = `// AUTO-GENERATED BY scripts/generate_isa.js
// DO NOT EDIT MANUALLY

use crate::vm::Vm;
use crate::stack::VmError;
use crate::handlers::*;

pub type HandlerFn = fn(&mut Vm) -> Result<bool, VmError>;

pub fn get_dispatch_table() -> [HandlerFn; 256] {
    let mut table: [HandlerFn; 256] = [op_invalid; 256];
`;

for (let i = 0; i < OPCODES.length; i++) {
    const op = OPCODES[i];
    const byte = bytes[i];
    const handler = `op_${op.toLowerCase()}`;
    dispatchTableContent += `    table[${byte}] = ${handler};\n`;
}

dispatchTableContent += `    table
}
`;
fs.writeFileSync(path.join(__dirname, '../crates/vm-core/src/dispatch_table.rs'), dispatchTableContent);
